// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authnpg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type User struct {
	ID           string
	Username     string
	DisplayName  string
	Email        pgtype.Text
	StudentNo    pgtype.Text
	EmployeeNo   pgtype.Text
	Status       string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID string
	Role   string
}
