// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package authnpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (id, user_id, token_hash, expires_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, created_at, last_seen_at
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM auth_sessions
WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM auth_sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM auth_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at, last_seen_at
FROM auth_sessions
WHERE token_hash = $1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserAuthByID = `-- name: GetUserAuthByID :one
SELECT id, username, display_name, status, COALESCE(password_hash, '')::text AS password_hash
FROM users
WHERE id = $1
`

type GetUserAuthByIDRow struct {
	ID           string
	Username     string
	DisplayName  string
	Status       string
	PasswordHash string
}

func (q *Queries) GetUserAuthByID(ctx context.Context, id string) (GetUserAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByID, id)
	var i GetUserAuthByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Status,
		&i.PasswordHash,
	)
	return i, err
}

const getUserAuthByUsername = `-- name: GetUserAuthByUsername :one
SELECT id, username, display_name, status, COALESCE(password_hash, '')::text AS password_hash
FROM users
WHERE lower(username) = lower($1)
`

type GetUserAuthByUsernameRow struct {
	ID           string
	Username     string
	DisplayName  string
	Status       string
	PasswordHash string
}

func (q *Queries) GetUserAuthByUsername(ctx context.Context, lower string) (GetUserAuthByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByUsername, lower)
	var i GetUserAuthByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Status,
		&i.PasswordHash,
	)
	return i, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role
FROM user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateUserPassword = `-- name: RotateUserPassword :execrows
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type RotateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) RotateUserPassword(ctx context.Context, arg RotateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :one
UPDATE auth_sessions
SET last_seen_at = $2, expires_at = $3
WHERE id = $1
RETURNING id, user_id, token_hash, expires_at, created_at, last_seen_at
`

type TouchSessionParams struct {
	ID         string
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.ID, arg.LastSeenAt, arg.ExpiresAt)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
